### ISSUE TITLE
Where do you get cracked games?

### ISSUE THREAD

**Issue by istituzionealsole** [WhySooooFurious/My-Mac-Repo#2]
I've seen some websites on reddit's mega threads such as nmac and cmacked but they don't really have a lot

For examples I am looking for the stray game, I've found a torrent on a website but have no idea if it's reliable or not (there are no reviews on reddit)

**Comment by WhySooooFurious** [comment]
We do not condone piracy. 

The reason we pirate is because we can't be stuffed buying a ton of games.

Closed.

**Comment by WhySooooFurious** [comment]
We do not condone piracy.

The reason we pirate is because we can't be stuffed buying a ton of games.

Closed.

**Comment by istituzionealsole** [comment]
lmao, if you don't condone piracy do not pirate, or at least do not publicise it on the internet

**Comment by WhySooooFurious** [comment]
You calling me a clown?

Not the one begging for links coz hes a dumbfuck and doesn't know how to do jack shit.

Fuck off you homeless dog

**Comment by istituzionealsole** [comment]
We don't condone piracy, we just pirate because we can't be stuffed by games lmaooo 🤡💀

**Comment by WhySooooFurious** [comment]
Yeah we can't. You know how many games we fucking test?

Stop being a dick and fuck off.

You're the one asking for fucking links you gay cunt
